name: Auto-Update
on:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodule to latest release
        run: |
          lastversion() { basename $(curl -fs -o/dev/null -w %{redirect_url} $1/releases/latest); }
          release=$(lastversion https://github.com/overviewer/Minecraft-Overviewer)
          git config --global user.name 'TheDruidsKeeper'
          git config --global user.email 'TheDruidsKeeper@users.noreply.github.com'
          cd minecraft-overviewer
          git fetch --tags
          git checkout --detach $(git rev-list -n 1 tags/$release)
          cd ..
          git commit -am "Automatic update to latest release"
          git push
