name: Build and Push Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Get tags from submodule
      id: submodule-tags
      run: |
        cd minecraft-overviewer
        git fetch --tags
        release=$(git describe --tags)
        echo "Using tag $release"
        echo "::set-output name=release::$release"
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: thedruidskeeper/minecraft-overviewer
        tag_with_ref: true
        tag_with_sha: true
        tags: |
          latest
          ${{ steps.submodule-tags.outputs.release }}
