name: Build and Push Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Get tags from submodule
      id: submodule-tags
      run: |
        cd minecraft-overviewer
        git fetch --tags
        release=$(git describe --tags)
        echo "Using tag $release"
        echo "::set-output name=release::$release"
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: thedruidskeeper/minecraft-overviewer
        tags: latest,${{ steps.submodule-tags.outputs.release }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: thedruidskeeper/minecraft-overviewer
