name: Update Submodule
on:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodule to most recent tag
        run: |
          git config --global user.name 'TheDruidsKeeper'
          git config --global user.email 'TheDruidsKeeper@users.noreply.github.com'
          cd minecraft-overviewer
          git fetch --tags
          lastTag=$(git for-each-ref --sort=creatordate --format '%(refname:lstrip=2)' refs/tags | tail -1)
          git checkout --detach $(git rev-list -n 1 tags/$lastTag)
          cd ..
          git diff-index --quiet HEAD || git commit -am "Automatic update to tag $lastTag"
          git push
